package com.mpos.lottery.te.valueaddservice.airtime.support.spi.coobill;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * 
 */
@WebService(name = "RechargeMsisdn", targetNamespace = "http://tempuri.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RechargeMsisdn {

    /**
     * 
     * @param payerSubsId
     * @param subGoodsId
     * @param transactionId
     * @param payDoneCode
     * @param payMoney
     * @param payStatus
     * @param coinType
     * @param receiverSubsId
     * @param operResult
     * @param cmdType
     * @param cooMallID
     * @param requestDate
     * @param subGoodsMoney
     * @param signature
     * @param orderId
     * @param totalMoney
     * @return returns com.mpos.lottery.te.valueaddservice.spi.coobill.OrderPaymentItem
     */
    @WebMethod
    @WebResult(partName = "return")
    public OrderPaymentItem cancelMsisdn(@WebParam(name = "cmdType", partName = "cmdType") int cmdType,
            @WebParam(name = "transactionId", partName = "transactionId") long transactionId,
            @WebParam(name = "payerSubsId", partName = "payerSubsId") String payerSubsId,
            @WebParam(name = "receiverSubsId", partName = "receiverSubsId") String receiverSubsId,
            @WebParam(name = "cooMallID", partName = "cooMallID") String cooMallID,
            @WebParam(name = "orderId", partName = "orderId") String orderId,
            @WebParam(name = "totalMoney", partName = "totalMoney") double totalMoney,
            @WebParam(name = "coinType", partName = "coinType") int coinType,
            @WebParam(name = "subGoodsId", partName = "subGoodsId") String subGoodsId,
            @WebParam(name = "subGoodsMoney", partName = "subGoodsMoney") double subGoodsMoney,
            @WebParam(name = "requestDate", partName = "requestDate") long requestDate,
            @WebParam(name = "payDoneCode", partName = "payDoneCode") String payDoneCode,
            @WebParam(name = "payMoney", partName = "payMoney") double payMoney,
            @WebParam(name = "payStatus", partName = "payStatus") int payStatus,
            @WebParam(name = "operResult", partName = "operResult") int operResult,
            @WebParam(name = "signature", partName = "signature") byte[] signature);

    /**
     * 
     * @param reqTransid
     * @param telNo
     * @return returns com.mpos.lottery.te.valueaddservice.spi.coobill.OrderPaymentItem
     */
    @WebMethod
    @WebResult(partName = "return")
    public OrderPaymentItem queryMsisdn(@WebParam(name = "telNo", partName = "telNo") String telNo,
            @WebParam(name = "reqTransid", partName = "reqTransid") String reqTransid);

    /**
     * 
     * @param msisdn
     * @param password
     * @param agent
     * @return returns com.mpos.lottery.te.valueaddservice.spi.coobill.GetMsisdnResult
     */
    @WebMethod(operationName = "GetMsisdn")
    @WebResult(partName = "return")
    public GetMsisdnResult getMsisdn(@WebParam(name = "agent", partName = "agent") String agent,
            @WebParam(name = "password", partName = "password") String password,
            @WebParam(name = "msisdn", partName = "msisdn") String msisdn);

    /**
     * 
     * @param amount
     * @param refTrx
     * @param msisdn
     * @param password
     * @param agent
     * @return returns com.mpos.lottery.te.valueaddservice.spi.coobill.TopupMsisdnResult
     */
    @WebMethod(operationName = "TopupMsisdn")
    @WebResult(partName = "return")
    public TopupMsisdnResult topupMsisdn(@WebParam(name = "agent", partName = "agent") String agent,
            @WebParam(name = "password", partName = "password") String password,
            @WebParam(name = "msisdn", partName = "msisdn") String msisdn,
            @WebParam(name = "amount", partName = "amount") int amount,
            @WebParam(name = "refTrx", partName = "refTrx") String refTrx);

}
