package com.mpos.lottery.te.valueaddservice.vat;

import com.mpos.lottery.te.common.dao.BaseEntity;
import com.mpos.lottery.te.config.exception.SystemException;
import com.mpos.lottery.te.gamespec.game.GameType;
import com.mpos.lottery.te.gamespec.sale.BaseTicket;
import com.mpos.lottery.te.trans.domain.Transaction;
import com.mpos.lottery.te.valueaddservice.vat.web.VatSaleTransactionDto;

import org.springframework.beans.BeanUtils;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "VAT_TRANSACTION_RECORDS")
public class VatSaleTransaction extends BaseEntity {
    private static final long serialVersionUID = -7883678363482996148L;
    public static final int STATUS_VALID = 1;
    public static final int STATUS_INVALID = 0;

    /**
     * The reference NO. which will be printed on VAT receipt.
     */
    @Column(name = "VAT_REFERENCE_NO")
    private String vatRefNo;
    @Column(name = "OPERATOR_ID")
    private String operatorId;
    @Column(name = "MERCHANT_ID")
    private long merchantId;
    // @Column(name = "TAX_ID")
    // private String taxId;
    @Column(name = "FROM_VAT_CUSTOMER_ID")
    private String sellerCompanyId;
    @Column(name = "TO_VAT_CUSTOMER_ID")
    private String buyerCompanyId;

    /**
     * For example, vat amount is 950, rate is 10%, the base amount of ticket is 100, then 950 * 10% = 95, in this case
     * vatTotalAmount is 950, vatRateTotalAmount is 95, and saleTotalAmount is 100(95 will be round up to 100).
     */
    @Column(name = "VAT_TOTAL_AMOUNT")
    private BigDecimal vatTotalAmount = new BigDecimal("0");
    @Column(name = "VAT_RATE_AMOUNT")
    private BigDecimal vatRateTotalAmount = new BigDecimal("0");
    @Column(name = "TOTAL_SALE_AMOUNT")
    private BigDecimal saleTotalAmount = new BigDecimal("0");

    @Column(name = "TE_TRANSACTION_ID")
    private String transactionId;
    @Column(name = "VAT_CATEGORY_ID")
    private String vatId;
    @Column(name = "GAME_TYPE_ID")
    private int gameType = GameType.UNDEF.getType();
    @Column(name = "GAME_INSTANCE_ID")
    private String gameInstanceId;
    @Column(name = "SERIAL_NUMBER")
    private String ticketSerialNo;
    @Column(name = "VAT_MERCHANT_TYPE_ID")
    private String businessType;
    // refer to STATUS_XX
    @Column(name = "STATUS")
    private int status = VatSaleTransaction.STATUS_VALID;
    /**
     * The client local timestamp, generated by client.
     */
    @Column(name = "CLIENT_TIMESTAMP")
    private Date transTimestampRef;

    // -------------------------------------------------
    // below fields are mainly for XML mapping purpose
    // -------------------------------------------------
    /**
     * The tax reference No. of buyer. Only present when client is in B2B mode.
     */
    @Transient
    private String buyerTaxNo;
    /**
     * Get the rate from <code>Vat2Game</code>.
     */
    @Transient
    private BigDecimal vatRate = new BigDecimal("0");
    @Transient
    private String vatCode;
    @Transient
    private int statusCode = SystemException.CODE_OK;
    /**
     * The ticket associated with VAT sale transaction.
     */
    @Transient
    private BaseTicket ticket;

    public VatSaleTransaction() {
    }

    public VatSaleTransaction(VatSaleTransactionDto dto) {
        BeanUtils.copyProperties(dto, this);
    }

    public void mergeTransaction(Transaction trans) {
        // simply use the same ID with transaction
        this.setId(trans.getId());
        this.setCreateTime(trans.getCreateTime());
        this.setUpdateTime(this.getCreateTime());
        this.operatorId = trans.getOperatorId();
        this.merchantId = trans.getMerchantId();
        this.transactionId = trans.getId();
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    public long getMerchantId() {
        return merchantId;
    }

    public void setMerchantId(long merchantId) {
        this.merchantId = merchantId;
    }

    public String getSellerCompanyId() {
        return sellerCompanyId;
    }

    public void setSellerCompanyId(String sellerCompanyId) {
        this.sellerCompanyId = sellerCompanyId;
    }

    public String getBuyerCompanyId() {
        return buyerCompanyId;
    }

    public void setBuyerCompanyId(String buyerCompanyId) {
        this.buyerCompanyId = buyerCompanyId;
    }

    public BigDecimal getSaleTotalAmount() {
        return saleTotalAmount;
    }

    public void setSaleTotalAmount(BigDecimal saleTotalAmount) {
        this.saleTotalAmount = saleTotalAmount;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getVatId() {
        return vatId;
    }

    public void setVatId(String vatId) {
        this.vatId = vatId;
    }

    public int getGameType() {
        return gameType;
    }

    public void setGameType(int gameType) {
        this.gameType = gameType;
    }

    public String getGameInstanceId() {
        return gameInstanceId;
    }

    public void setGameInstanceId(String gameInstanceId) {
        this.gameInstanceId = gameInstanceId;
    }

    public String getTicketSerialNo() {
        return ticketSerialNo;
    }

    public void setTicketSerialNo(String ticketSerialNo) {
        this.ticketSerialNo = ticketSerialNo;
    }

    public String getBusinessType() {
        return businessType;
    }

    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }

    public BigDecimal getVatTotalAmount() {
        return vatTotalAmount;
    }

    public void setVatTotalAmount(BigDecimal vatTotalAmount) {
        this.vatTotalAmount = vatTotalAmount;
    }

    public BigDecimal getVatRateTotalAmount() {
        return vatRateTotalAmount;
    }

    public void setVatRateTotalAmount(BigDecimal vatRateTotalAmount) {
        this.vatRateTotalAmount = vatRateTotalAmount;
    }

    public String getVatRefNo() {
        return vatRefNo;
    }

    public void setVatRefNo(String vatRefNo) {
        this.vatRefNo = vatRefNo;
    }

    public String getBuyerTaxNo() {
        return buyerTaxNo;
    }

    public void setBuyerTaxNo(String buyerTaxNo) {
        this.buyerTaxNo = buyerTaxNo;
    }

    public BigDecimal getVatRate() {
        return vatRate;
    }

    public void setVatRate(BigDecimal vatRate) {
        this.vatRate = vatRate;
    }

    public String getVatCode() {
        return vatCode;
    }

    public void setVatCode(String vatCode) {
        this.vatCode = vatCode;
    }

    public BaseTicket getTicket() {
        return ticket;
    }

    public void setTicket(BaseTicket ticket) {
        this.ticket = ticket;
    }

    public Date getTransTimestampRef() {
        return transTimestampRef;
    }

    public void setTransTimestampRef(Date transTimestampRef) {
        this.transTimestampRef = transTimestampRef;
    }

    public int getStatusCode() {
        return statusCode;
    }

    public void setStatusCode(int statusCode) {
        this.statusCode = statusCode;
    }

}
