
-- TE_TRANSACTION
insert into TE_TRANSACTION( 
    ID,OPERATOR_ID,GPE_ID,DEV_ID,MERCHANT_ID,CREATE_TIME,TYPE,TRANS_TIMESTAMP,RESPONSE_CODE,
    TICKET_SERIAL_NO,TRACE_MESSAGE_ID,BATCH_NO,GAME_ID,VERSION,TOTAL_AMOUNT,DESTINATION_OPEATOR,CANCEL_TE_TRANSACTION_ID,CANCEL_TRANSACTION_TYPE
) values(
    'TRANS-transfer_james-1111','OPERATOR-111','GPE-111',111,111,sysdate,
    116,sysdate,200,null,'telecovoucher_msg_1','20092009','VOUCHER-1',0,100.0,'OPERATOR-111',null,0
); 

-- VAS_VOUCHER_SELLING_RECORDS


insert into BALANCE_TRANSACTIONS (ID, TE_TRANSACTION_ID, MERCHANT_ID, DEVICE_ID, OPERATOR_ID, OWNER_ID, OWNER_TYPE, PAYMENT_TYPE, TRANSACTION_TYPE, BALANCE_AMOUNT, COMMISION_AMOUNT, UPDATE_TIME, COMMISION_RATE, CREATE_TIME, STATUS)
    values (991, 'TRANS-transfer_james-1111', 111, 111, '1111', 'OPERATOR-111', 1, 2, 1161, 100, 1, sysdate, .01, sysdate, '1');

insert into BALANCE_TRANSACTIONS (ID, TE_TRANSACTION_ID, MERCHANT_ID, DEVICE_ID, OPERATOR_ID, OWNER_ID, OWNER_TYPE, PAYMENT_TYPE, TRANSACTION_TYPE, BALANCE_AMOUNT, COMMISION_AMOUNT, UPDATE_TIME, COMMISION_RATE, CREATE_TIME, STATUS)
    values (992, 'TRANS-transfer_james-1111', 111, 111, 'OPERATOR-111', '1111', 1, 1, 1161, 100, 1, sysdate, .01, sysdate, '1');



