# -*- coding: UTF-8 -*-
# -------------------------------------------------------------
# Remove all comments from the SQL file generated by Oracle
# SQL developer.
# -------------------------------------------------------------

import sys

def clear_comments(file):
	input = open(file, "r")
	# generate a new output file
	output = open(file + ".new", "w")
	
	# remove all lines between first comment line and '----------------'
	in_comment_block = False
	for line in input:
		if line.strip().startswith("COMMENT ON"):
			in_comment_block = True
		if in_comment_block and line.strip().startswith("----------------"):
				in_comment_block = False
		if not in_comment_block:
			output.write(line)
	
	# close resource
	input.close()
	output.close();
	
if __name__ == "__main__":
	# sys.argv[0] is the file name of script.
	if len(sys.argv) != 2:
		print "[USAGE] python " + sys.argv[0] + " file"
	else :
		clear_comments(sys.argv[1])